INSERT INTO TB_CIDADE (ID_CIDADE, DS_CIDADE, DS_UF) VALUES (1, 'Brasília', 'DF');
INSERT INTO TB_CIDADE (ID_CIDADE, DS_CIDADE, DS_UF) VALUES (2, 'Ceilândia', 'DF');
INSERT INTO TB_CIDADE (ID_CIDADE, DS_CIDADE, DS_UF) VALUES (3, 'Samambaia', 'DF');
INSERT INTO TB_CIDADE (ID_CIDADE, DS_CIDADE, DS_UF) VALUES (4, 'Porto Seguro', 'BA');
